const original = [
  { id: 'k1', text: 'What is the capital city of Kenya?', options: ['Mombasa', 'Nairobi', 'Kisumu', 'Nakuru'], correctAnswer: 1 },
  { id: 'k2', text: 'Which county uses the code 039?', options: ['Mombasa', 'Kwale', 'Kilifi', 'Lamu'], correctAnswer: 1 },
  { id: 'k3', text: 'What is the capital city of France?', options: ['Berlin', 'Madrid', 'Paris', 'Rome'], correctAnswer: 2 },
  { id: 'k4', text: 'Who is the current President of Kenya?', options: ['Uhuru Kenyatta', 'William Ruto', 'Raila Odinga', 'Mwai Kibaki'], correctAnswer: 1 },
  { id: 'k5', text: 'Which ocean borders Kenya to the East?', options: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'], correctAnswer: 1 },
  { id: 'k6', text: 'What is the national language of Kenya?', options: ['English', 'Kikuyu', 'Swahili', 'Sheng'], correctAnswer: 2 },
  { id: 'k7', text: 'What is the highest mountain in Kenya?', options: ['Mt. Kilimanjaro', 'Mt. Kenya', 'Mt. Elgon', 'Mt. Longonot'], correctAnswer: 1 },
  { id: 'k8', text: 'In which year did Kenya gain independence?', options: ['1960', '1963', '1964', '1952'], correctAnswer: 1 },
  { id: 'k9', text: 'Which famous wildlife migration happens in the Maasai Mara?', options: ['Elephant', 'Wildebeest', 'Zebra', 'Lion'], correctAnswer: 1 },
  { id: 'k10', text: 'Which is the longest river in Kenya?', options: ['Athi River', 'Mara River', 'Tana River', 'Ewaso Ng\'iro'], correctAnswer: 2 },
  { id: 'k11', text: 'Which country borders Kenya to the South?', options: ['Uganda', 'Ethiopia', 'Somalia', 'Tanzania'], correctAnswer: 3 },
  { id: 'k12', text: 'What is the official currency of Kenya?', options: ['Dollar', 'Euro', 'Kenyan Shilling', 'CFA Franc'], correctAnswer: 2 },
  { id: 'k13', text: 'Which is the largest lake in Kenya?', options: ['Lake Nakuru', 'Lake Victoria', 'Lake Turkana', 'Lake Naivasha'], correctAnswer: 1 },
  { id: 'k14', text: 'Who was the first President of Kenya?', options: ['Daniel arap Moi', 'Jomo Kenyatta', 'Oginga Odinga', 'Tom Mboya'], correctAnswer: 1 },
  { id: 'k15', text: 'Which of the following is NOT part of the Big Five?', options: ['Lion', 'Leopard', 'Cheetah', 'Rhino'], correctAnswer: 2 },
  { id: 'k16', text: 'What is the name of the Kenyan national football team?', options: ['Super Eagles', 'Harambee Stars', 'Black Stars', 'Taifa Stars'], correctAnswer: 1 },
  { id: 'k17', text: 'What color is the top stripe of the Kenyan flag?', options: ['Red', 'Green', 'Black', 'White'], correctAnswer: 2 },
  { id: 'k18', text: 'What does the Swahili phrase "Hakuna Matata" mean?', options: ['Good Morning', 'Thank You', 'No Worries', 'Welcome'], correctAnswer: 2 },
  { id: 'k19', text: 'Which Kenyan athlete is widely considered the greatest marathoner?', options: ['Eliud Kipchoge', 'David Rudisha', 'Paul Tergat', 'Julius Yego'], correctAnswer: 0 },
  { id: 'k20', text: 'What is the airport code for Jomo Kenyatta International Airport?', options: ['JKA', 'NBO', 'KNY', 'MBA'], correctAnswer: 1 },
  { id: 'k21', text: 'Which city hosts the United Nations Environment Programme (UNEP) headquarters?', options: ['Geneva', 'New York', 'Nairobi', 'Addis Ababa'], correctAnswer: 2 },
  { id: 'k22', text: 'Which county uses the code 001?', options: ['Nairobi', 'Mombasa', 'Kisumu', 'Kwale'], correctAnswer: 1 },
  { id: 'k23', text: 'Which county uses the code 016?', options: ['Machakos', 'Kitui', 'Makueni', 'Kiambu'], correctAnswer: 0 },
  { id: 'k24', text: 'Which county uses the code 032?', options: ['Baringo', 'Uasin Gishu', 'Nakuru', 'Narok'], correctAnswer: 2 },
  { id: 'k25', text: 'Which county uses the code 042?', options: ['Homa Bay', 'Migori', 'Kisii', 'Kisumu'], correctAnswer: 3 },
  { id: 'k26', text: 'Which Kenyan lake is most famous for its flamingos?', options: ['Lake Bogoria', 'Lake Nakuru', 'Lake Baringo', 'Lake Magadi'], correctAnswer: 1 },
  { id: 'k27', text: 'Who is the current CEO of Safaricom (as of 2024)?', options: ['Michael Joseph', 'Bob Collymore', 'Peter Ndegwa', 'James Mwangi'], correctAnswer: 2 },
  { id: 'k28', text: 'What is the common staple food in Kenya made from maize flour?', options: ['Chapati', 'Pilau', 'Ugali', 'Nyama Choma'], correctAnswer: 2 },
  { id: 'k29', text: 'Which Kenyan won the Nobel Peace Prize in 2004?', options: ['Wangari Maathai', 'Lupita Nyong\'o', 'Ngugi wa Thiong\'o', 'Richard Leakey'], correctAnswer: 0 },
  { id: 'k30', text: 'Which is the largest national park in Kenya?', options: ['Nairobi National Park', 'Amboseli', 'Tsavo', 'Maasai Mara'], correctAnswer: 2 },
  { id: 'k31', text: 'How many counties are there in Kenya?', options: ['42', '45', '47', '50'], correctAnswer: 2 },
  { id: 'k32', text: 'What is the acronym for Kenya\'s modern high-speed railway?', options: ['SGR', 'KRC', 'MRT', 'BRT'], correctAnswer: 0 },
  { id: 'k33', text: 'Which famous community is known for inhabiting the Maasai Mara region?', options: ['Kikuyu', 'Luo', 'Maasai', 'Kalenjin'], correctAnswer: 2 },
  { id: 'k34', text: 'Nairobi is commonly referred to as the "Green City in the..."?', options: ['Sun', 'Valley', 'Clouds', 'Savannah'], correctAnswer: 0 },
  { id: 'k35', text: 'Which major Kenyan town is located exactly on the Equator?', options: ['Eldoret', 'Nanyuki', 'Naivasha', 'Isiolo'], correctAnswer: 1 },
  { id: 'k36', text: 'Lamu Island is located in which body of water?', options: ['Lake Victoria', 'Indian Ocean', 'Red Sea', 'Lake Turkana'], correctAnswer: 1 },
  { id: 'k37', text: 'Who wrote the famous novel "Weep Not, Child"?', options: ['Binyavanga Wainaina', 'Margaret Ogola', 'Ngugi wa Thiong\'o', 'Meja Mwangi'], correctAnswer: 2 },
  { id: 'k38', text: 'What nickname is often given to Kenya\'s growing tech ecosystem?', options: ['Silicon Valley', 'Silicon Savannah', 'Tech Cape', 'AfriTech'], correctAnswer: 1 },
  { id: 'k39', text: 'What is the official Swahili word for tea?', options: ['Kahawa', 'Maji', 'Chai', 'Maziwa'], correctAnswer: 2 },
  { id: 'k40', text: 'What is the international dialing code for Kenya?', options: ['+255', '+256', '+254', '+250'], correctAnswer: 2 }
];

const newQs = [];
const templates = [
  'We asked 100 people: Name something you do when you wake up.',
  'Name a reason you might be late to work.',
  'Name something you associate with a dog.',
  'Name a food that is notoriously messy to eat.',
  'Name something you keep in your car glovebox.',
  'Name a popular pizza topping.',
  'Name a country famous for its chocolate.',
  'Name an activity people do at the beach.',
  'Name something you need to buy before a road trip.',
  'Name a profession that requires a uniform.',
  'Name something people lose all the time.',
  'Name an animal you might see at the zoo.',
  'Name a reason someone might cry.',
  'Name a fruit that is red.',
  'Name something you might find in a desk drawer.',
  'Name a popular board game.',
  'Name something people hate doing.',
  'Name a common fear.',
  'Name a popular ice cream flavor.',
  'Name a holiday people celebrate with family.',
  'Name a popular sport in Kenya.',
  'Name something you bring to a picnic.',
  'Name a common subject taught in school.',
  'Name something that has keys.',
  'Name a popular social media platform.',
  'Name something you find in a kitchen.',
  'Name a bird that cannot fly.',
  'Name a popular movie genre.',
  'Name something you might find in a bathroom.',
  'Name a transportation method.',
  'Name a color in the rainbow.',
  'Name something you buy at a bakery.',
  'Name a planet in our solar system.',
  'Name a musical instrument.',
  'Name something you wear on your head.',
  'Name a country bordering the Mediterranean Sea.',
  'Name a standard unit of measurement.',
  'Name something associated with witches.',
  'Name a common vegetable.',
  'Name something you do before going to sleep.'
];

const optionsLists = [
  ['Brush teeth', 'Check phone', 'Drink water', 'Shower'],
  ['Traffic', 'Overslept', 'Car trouble', 'Sick'],
  ['Bone', 'Bark', 'Leash', 'Park'],
  ['Spaghetti', 'Ribs', 'Tacos', 'Burgers'],
  ['Napkins', 'Manual', 'Registration', 'Sunglasses'],
  ['Pepperoni', 'Mushrooms', 'Onions', 'Sausage'],
  ['Switzerland', 'Belgium', 'USA', 'France'],
  ['Swim', 'Sunbathe', 'Read', 'Volleyball'],
  ['Snacks', 'Gas', 'Drinks', 'Map'],
  ['Police', 'Nurse', 'Firefighter', 'Chef'],
  ['Keys', 'Phone', 'Wallet', 'Glasses'],
  ['Lion', 'Monkey', 'Elephant', 'Giraffe'],
  ['Sad', 'Happy', 'Onions', 'Pain'],
  ['Apple', 'Strawberry', 'Cherry', 'Tomato'],
  ['Pens', 'Paperclips', 'Stapler', 'Sticky notes'],
  ['Monopoly', 'Scrabble', 'Chess', 'Clue'],
  ['Laundry', 'Dishes', 'Cleaning', 'Working'],
  ['Spiders', 'Heights', 'Public speaking', 'Dark'],
  ['Vanilla', 'Chocolate', 'Strawberry', 'Mint'],
  ['Christmas', 'Thanksgiving', 'Easter', 'New Year'],
  ['Football', 'Athletics', 'Rugby', 'Safari Rally'],
  ['Blanket', 'Sandwiches', 'Basket', 'Frisbee'],
  ['Mathematics', 'English', 'Science', 'History'],
  ['Piano', 'Keyboard', 'Keychain', 'Lock'],
  ['WhatsApp', 'TikTok', 'Instagram', 'Facebook'],
  ['Stove', 'Refrigerator', 'Microwave', 'Blender'],
  ['Ostrich', 'Penguin', 'Kiwi', 'Emu'],
  ['Action', 'Comedy', 'Horror', 'Sci-Fi'],
  ['Toothbrush', 'Soap', 'Towel', 'Mirror'],
  ['Matatu', 'Train', 'Airplane', 'Motorcycle'],
  ['Red', 'Blue', 'Yellow', 'Green'],
  ['Bread', 'Cake', 'Croissant', 'Donut'],
  ['Mars', 'Jupiter', 'Saturn', 'Venus'],
  ['Guitar', 'Piano', 'Violin', 'Drums'],
  ['Cap', 'Helmet', 'Hat', 'Beanie'],
  ['Italy', 'Spain', 'Greece', 'Egypt'],
  ['Meter', 'Kilogram', 'Liter', 'Second'],
  ['Broomstick', 'Black cat', 'Cauldron', 'Spellbook'],
  ['Carrot', 'Cabbage', 'Spinach', 'Onion'],
  ['Brush teeth', 'Set alarm', 'Read book', 'Turn off lights']
];

for(let i=0; i<900; i++) {
  let qText = templates[i % templates.length];
  let opts = optionsLists[i % optionsLists.length];
  newQs.push({
    id: 'f' + (i+1),
    text: qText,
    options: opts,
    correctAnswer: 0
  });
}

const allQs = [...original, ...newQs];
module.exports = allQs;
